InFact-coop/LCN

src/elm/Components/Navbar.elm, src/elm/Components/ViewStories.elm
And sorts out all the final names
=> Style the navbar

src/css/index.css, src/elm/Components/Navbar.elm, src/elm/Routes/WorkerView.elm
=> style the forms

src/elm/Types.elm
=> Write out model and add union types

src/elm/State.elm, src/elm/Types.elm, src/elm/Views/Home.elm
=> working update to model on law centre

src/elm/Data/PostComment.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/AddComment.elm, src/server/routers/api_router.js
=> Post comments

src/elm/Components/Button.elm, src/elm/Helpers.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/AddStats.elm
+ Created helper for converting union types to labels
+ hooked up add-stats view to model
Relates #60
=> Quant form view

src/elm/Components/Button.elm, src/elm/Data/CommentType.elm, src/elm/Data/LawArea.elm, src/elm/Data/LawCentre.elm, src/elm/Helpers.elm, src/elm/Requests/PostComment.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/AddComment.elm, src/elm/Views/AddStats.elm, src/elm/Views/Home.elm, src/elm/Views/ListComments.elm
* Make data helper modules
* Start scaffolding ListComments view
relates #67
=> Get comments

src/elm/Data/Comment.elm, src/elm/Helpers.elm, src/elm/Requests/PostReply.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/ListComments.elm
* Send comment replies to airtable
* Style comments and replied-to comments differently 
resolves #62
=> Reply to functionality

public/index.html, src/css/_variables.css, src/elm/Components/Button.elm, src/elm/Components/CommentModal.elm, src/elm/Components/Nav.elm, src/elm/Components/StatsModal.elm, src/elm/Components/StyleHelpers.elm, src/elm/Data/LawArea.elm, src/elm/Router.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/AddComment.elm, src/elm/Views/AddStats.elm, src/elm/Views/Home.elm, src/elm/Views/ListComments.elm
* Add comment modal
* Implement font hierarchy
* Style for mobile
=> Comment modal

src/css/_variables.css, src/elm/Router.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/Home.elm
=> Logout links

UserTesting.md
=> Add user testing script

Presentation.md, src/elm/Components/Button.elm, src/elm/Components/StatsThisWeek.elm, src/elm/Views/AddComment.elm
* Add presentation readme
* Minor style changes
=> Presentation readme

server/views/partials/new-password-input.hbs, server/views/partials/password-input.hbs, server/views/reset-password.hbs, server/views/signup.hbs
+ Split out password HBS partial into new-password and password (for login)
+ New, tested regex
+ Clearer instructions
=> Fixed password clash issues #92 #95

server/routers/api.js, src/css/_custom.css, src/css/_variables.css, src/elm/Components/Nav.elm, src/elm/Data/Role.elm, src/elm/Requests/GetUserDetails.elm, src/elm/Requests/PostNewUserDetails.elm, src/elm/Router.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/SplashScreen.elm
+ Populating user information on login from database
+ Redirecting from Splash Screen depending on this information
+ Bomb millisecond splash screen
Fixes #111
=> Populate the user

src/elm/Components/Button.elm, src/elm/Components/StatsModal.elm, src/elm/Components/StatsThisWeek.elm, src/elm/State.elm
+ Made responsive
+ submitEnabled check on ToggleAgency
+ Minor copy changes
Fixes #100
=>  + Updated stats modal

server/models/user.js
=> Add missing fields to User schema

src/elm/Router.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/Snapshot.elm
and removes unused view.
Resolves #96
=> Adds sticky navigation

src/css/_custom.css, src/css/_variables.css, src/elm/Views/ListComments.elm
+ Switcharoo of Comment buttons
+ Created "Send" button for reply comments which shows on desktop view
Resolves #104
=> Smaller copy changes

public/assets/add_blue.svg, public/assets/add_green.svg, public/assets/add_orange.svg, public/assets/add_pink.svg, server/config/passport.js, server/controllers/api.js, server/helpers/airtable_helpers.js, server/helpers/db_helpers.js, server/models/user.js, server/routers/api.js, src/css/_variables.css, src/elm/Components/Nav.elm, src/elm/Components/StatsThisWeek.elm, src/elm/Data/Comment.elm, src/elm/Requests/GetComments.elm, src/elm/Requests/PostUpvote.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/ListComments.elm
=> Functional likes

server/views/partials/full-name-input.hbs, src/elm/Views/ListComments.elm
* Add missing onClick msg
* Allow dashes in signup name field
=> Add missing onClick Msg and allow dashes in name field

server/helpers/email_helpers.js, server/views/email/sign-up-email.hbs, server/views/email/signup-confirmation-email.hbs, server/views/partials/new-password-input.hbs, src/elm/Components/StatsThisWeek.elm, src/elm/Views/AddStats.elm
=> Update email copy

package.json, src/css/_custom.css, src/elm/Components/StatsThisWeek.elm, src/elm/Components/StyleHelpers.elm, src/elm/Main.elm, src/elm/State.elm, src/elm/Views/BeforeYouBegin.elm
Create numerical non-sliding number component
Resolves #139
=> Number component

server/routers/api.js, src/elm/Components/StatsThisWeek.elm, src/elm/Requests/PostStats.elm, src/elm/State.elm, src/elm/Types.elm, src/elm/Views/AddStats.elm
=> Added and amended PostStats questions

src/elm/Components/Nav.elm, src/elm/Router.elm, src/elm/State.elm
+ Resize nav logo
+ Autoredirect and url change
Relates #145
=> Redirect triggers router

server/routers/route_middleware.js, src/elm/Components/StatsThisWeek.elm, src/elm/Views/AddStats.elm, src/elm/Views/BeforeYouBegin.elm
Resolves #160
resolves #161
resolves #158
=> Bughunting

server/views/layouts/main.hbs, server/views/onboarding.hbs
=> Disable login button until last onboarding slide

server/controllers/auth.js, server/routers/route_middleware.js, server/views/layouts/main.hbs, server/views/onboarding.hbs, src/css/_custom.css
- Make onboarding root view
- Make flickity autoscroll and wraparound
=> Onboarding

server/controllers/auth.js, server/helpers/email_helpers.js, server/routers/route_middleware.js, server/views/invite-users.hbs, server/views/layouts/main.hbs, server/views/onboarding.hbs, src/css/_custom.css, src/elm/Components/LawAreaCheckbox.elm, src/elm/Views/BeforeYouBegin.elm
+ Pass token through onboarding view  …
+ Conditionally render "Get started" or "Login" button depending on presence of token
+ Pass through token to signup view
+ Change autoplay on onboarding carousel to 3.5 seconds
+ Appropriately coloured checkboxes  …
+ create url const before render fix
+ Show "..." button on before you begin loading
Resolves #167 🎉
=> Onboarding signup
